packages:
  - "packages/*"
  - "apps/*"
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.9.18'
  - '@turbo/darwin-arm64@2.9.18'
  - '@turbo/linux-64@2.9.18'
  - '@turbo/linux-arm64@2.9.18'
  - '@turbo/windows-64@2.9.18'
  - '@turbo/windows-arm64@2.9.18'
  - turbo@2.9.18
